// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tecxkhednqyyxwcxkpul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlY3hraGVkbnF5eXh3Y3hrcHVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwNDk4NjgsImV4cCI6MjA1MTYyNTg2OH0.lMUWrLK5l3RLNJMym_XOgxe9cw1uYxugHkgCVqsqowQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);